# Generated by Django 5.2.11 on 2026-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='builder_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
