# Generated by Django 5.2.11 on 2026-02-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resume_builder_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='grammar_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='grammar_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='keyword_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
