# Generated by Django 5.2.11 on 2026-02-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_referrals'),
    ]

    operations = [
        migrations.DeleteModel(name='ReferralContact'),
        migrations.DeleteModel(name='ReferralJob'),
        migrations.DeleteModel(name='ReferralTemplate'),
    ]

