# Generated by Django 5.2.11 on 2026-02-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_remove_referrals'),
    ]

    operations = [
        migrations.RemoveField(model_name='resumeanalysis', name='grammar_issues'),
        migrations.RemoveField(model_name='resumeanalysis', name='grammar_score'),
    ]

