# Generated by Django 5.2.11 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_resumeanalysis_user_and_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
