# Generated by Django 6.0.4 on 2026-04-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_userprofile_dummy_data_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttemplate',
            name='template_scope',
            field=models.CharField(choices=[('system', 'System'), ('user_based', 'User Based')], default='user_based', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjecttemplate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_templates', to='analyzer.userprofile'),
        ),
    ]
