name: Production Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd ~/ReactAct

            echo "Pull latest code"
            git pull origin master

            echo "Backend setup"
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput

            echo "Frontend build"
            cd ../frontend
            npm install
            npm run build

            echo "Update web files"
            sudo rm -rf /var/www/reactact/*
            sudo cp -r dist/* /var/www/reactact/

            echo "Restart backend"
            sudo systemctl restart gunicorn